package model

import "strings"

// LlmComment represents a code review comment generated by the LLM.
type LlmComment struct {
	Path           string `json:"path"`
	Content        string `json:"content"`
	SuggestionCode string `json:"suggestion_code,omitempty"`
	ExistingCode   string `json:"existing_code,omitempty"`
	StartLine      int    `json:"start_line"`
	EndLine        int    `json:"end_line"`
	Thinking       string `json:"thinking,omitempty"`
	Severity       string `json:"severity,omitempty"`    // 严重级别: CRITICAL/HIGH/MEDIUM/LOW
	Category       string `json:"category,omitempty"`    // 分类: security/performance/ correctness/maintainability
}

// Severity 级别定义
const (
	SeverityCritical = "CRITICAL"
	SeverityHigh     = "HIGH"
	SeverityMedium   = "MEDIUM"
	SeverityLow      = "LOW"
	SeverityDefault  = "MEDIUM" // 未标注时的默认级别
)

// SeverityChinese 返回中文严重级别标签
func SeverityChinese(s string) (string, string) {
	switch s {
	case SeverityCritical:
		return "严重", "\033[1;31m" // 红色粗体
	case SeverityHigh:
		return "高危", "\033[0;33m" // 黄色
	case SeverityMedium:
		return "中危", "\033[0;34m" // 蓝色
	case SeverityLow:
		return "低危", "\033[0;90m" // 灰色
	default:
		return "中危", "\033[0;34m"
	}
}

// ResetColor ANSI 颜色重置
const ResetColor = "\033[0m"

// KeywordSeverity 通过评论内容关键词推断严重级别
func KeywordSeverity(content string) string {
	contentLower := strings.ToLower(content)
	keywords := map[string]string{
		SeverityCritical: "security|vulnerability|injection|xss|sqli|secret|credential|password|token|api.key|sql injection|remote code|arbitrary|critical|严重",
		SeverityHigh:     "deadlock|race condition|memory leak|data loss|corruption|panic|crash|高危|denial of service|dos|ssrf|path traversal",
		SeverityMedium:   "performance|n+1|resource leak|memory|goroutine|dead code|error handling|bound|null pointer|nil|中危",
		SeverityLow:      "typo|spelling|naming|style|format|comment|低危|unused|import|whitespace",
	}
	for sev, pattern := range keywords {
		for _, kw := range strings.Split(pattern, "|") {
			if strings.Contains(contentLower, kw) {
				return sev
			}
		}
	}
	return SeverityDefault
}

// CodeReviewResult holds raw LLM-generated review suggestion for a code segment.
type CodeReviewResult struct {
	RelevantFile      string `json:"relevant_file"`
	SuggestionContent string `json:"suggestion_content"`
	ExistingCode      string `json:"existing_code"`
	SuggestionCode    string `json:"suggestion_code"`
}
